# Objective: Learning to Solve Basic Python Problems
- Tackle few simple problems relvant to AI/ML 
- Break a problem into smaller sub-problems. 
- Connecting the dots from sub-problems to coding-concepts. 
- Code-walkthrough + Putting it all together. 
- More focus on common errors and mistakes + reading function reference + fixing bugs 
- Exercise-problems for practice. 
- Introduce new concepts as we need. 
- Good programmers may not benifit much from this session.

# Problem 1 - Add two randomly generated NumPy matrices using loops
- Sub-problems
- Sub-problems ---> Coding Concepts
- Code Walkthrough + Mistakes
- Exercise: Add two randomly generated Numpy 3D-matrices(tensor) using loops

In [1]:
#Create random matrix A1 of size 4X3

import numpy as np
a1 = np.random.rand(5,4)
a2 = np.random.rand(5,4)
print(a1)
print(a1.shape)
print(a2)
print(a2.shape)

[[0.10254323 0.48939265 0.89989232 0.59263959]
 [0.24398972 0.69556807 0.46130706 0.6321916 ]
 [0.11663346 0.3870593  0.9789439  0.44620981]
 [0.32480146 0.60950671 0.05968952 0.77737873]
 [0.25001001 0.48757553 0.12556441 0.22807671]]
(5, 4)
[[0.06741127 0.79111397 0.53475488 0.31749514]
 [0.68616056 0.43654391 0.70935577 0.30863542]
 [0.14902814 0.13358825 0.81313866 0.96860715]
 [0.4599474  0.66444163 0.05506048 0.89185648]
 [0.21379292 0.86073576 0.20790419 0.13598249]]
(5, 4)


In [2]:
print(type(a1))

<class 'numpy.ndarray'>


In [3]:
#Using + operator on ndarrays

B = a1 + a2
print(B)

[[0.1699545  1.28050662 1.4346472  0.91013472]
 [0.93015029 1.13211197 1.17066283 0.94082702]
 [0.2656616  0.52064754 1.79208255 1.41481696]
 [0.78474886 1.27394834 0.11475    1.66923522]
 [0.46380293 1.34831129 0.3334686  0.3640592 ]]


In [4]:
# Saving rows and columns in variables r and c

(r,c) = a1.shape;
print(r,c)

5 4


In [12]:
#B[i,j] = A1[i,j] + A2[i,j]

D = np.zeros((5,4))

for i in range(r):
    for j in range(c):
        D[i,j] = a1[i,j] + a2[i,j];

print(D)

[[0.1699545  1.28050662 1.4346472  0.91013472]
 [0.93015029 1.13211197 1.17066283 0.94082702]
 [0.2656616  0.52064754 1.79208255 1.41481696]
 [0.78474886 1.27394834 0.11475    1.66923522]
 [0.46380293 1.34831129 0.3334686  0.3640592 ]]


### Time Complexity ? -- O(n^2)
### Space Complexity ? -- O(1) -- It is Constant

# Exercise 1 - Add two randomly generated NumPy 3D-matrices(tensor) using loops
HINT: B[i,j,k] = A1[i,j,k] + A2[i,j,k]

In [14]:
a1 = np.random.rand(3,3,3)
a2 = np.random.rand(3,3,3)
print(a1)
print(a1.shape)
print(a1.ndim)
print('******************************')
print(a2)
print(a2.shape)
print(a2.ndim)

[[[0.02478571 0.11218352 0.0703074 ]
  [0.59053019 0.64397501 0.61213608]
  [0.38304955 0.16342154 0.9265559 ]]

 [[0.03679117 0.32402016 0.54079149]
  [0.69795668 0.53604062 0.79735251]
  [0.18321763 0.62873189 0.53343948]]

 [[0.70714707 0.37548187 0.99426623]
  [0.62675681 0.23774236 0.88282928]
  [0.20931151 0.24397369 0.44646564]]]
(3, 3, 3)
3
******************************
[[[0.39820191 0.80003132 0.9497936 ]
  [0.04817745 0.29683696 0.54006112]
  [0.80492014 0.47722065 0.25618941]]

 [[0.41255058 0.18407117 0.6556666 ]
  [0.6377687  0.88937054 0.5077321 ]
  [0.16571438 0.10978829 0.06884843]]

 [[0.57590691 0.70774335 0.51857895]
  [0.64724601 0.59964253 0.61368581]
  [0.38670677 0.61461761 0.14909668]]]
(3, 3, 3)
3


In [15]:
(x,y,z) = a1.shape
print(x,y,z)

3 3 3


In [16]:
A = np.zeros((3,3,3))

for i in range(x):
    for j in range(y):
        for k in range(z):
            A[i,j,k] = a1[i,j,k] + a2[i,j,k]
print(A)

[[[0.42298763 0.91221484 1.02010101]
  [0.63870764 0.94081198 1.15219721]
  [1.18796969 0.64064219 1.18274531]]

 [[0.44934176 0.50809134 1.19645809]
  [1.33572538 1.42541116 1.30508461]
  [0.348932   0.73852018 0.6022879 ]]

 [[1.28305398 1.08322522 1.51284518]
  [1.27400282 0.83738489 1.49651508]
  [0.59601828 0.85859129 0.59556232]]]


# Problem 2 : Find if a given 2D-point is inside (or) outside a circle.
- Subproblems.
- Subproblems --> coding concepts.
- putting it all together.
- Exercise: Find if a given 2D point is inside (or) outside a rectangle ? 

- If there is a circle with center(Cx,Cy) and radius(r).
- If there is a point (Px,Py) and the distance between Center and point is (D).
- Then : 
1. If Distance(d) is less than radius(r)__[d < r]__ - The point is INSIDE circle.
2. If Distance(d) is equal to randius(r)__[d = r]__ - The point is ON circle.
3. If Distance(d) is more than radius(r)__[d > r]__ - The point is OUTSIDE circle.

### Distance Between Two Points = sqrt((Cx - Px)^2 + (Cy - Py)^2)

In [28]:
print("Enter Cx, Cy and r :")
(Cx, Cy, r) = input().split()

print(Cx,Cy,r)
print(Cx)
print(Cy)
print(r)

Enter Cx, Cy and r :
1 2 15
1 2 15
1
2
15


In [29]:
print("Enter Px and Py :")
(Px,Py) = input().split()

Enter Px and Py :
2 3


In [31]:
Cx = float(Cx)
Cy = float(Cy)
r = float(r)
Px = float(Px)
Py = float(Py)

import math
d = math.sqrt( (Cx - Px)**2 + (Cy - Py)**2 )

if d < r:
    print("P is inside a Circle.")
elif d == r:
    print("P is on a Circle.")
else:
    print("P is Outside a Circle.")

P is inside a Circle.


# Exercise 2 - Find if a point is inside or outside a rectangle.

In [54]:
print("Enter x1,y1,x2,y2 :")
(x1,y1,x2,y2) = map(float, input().split())

print(type(x1))

Enter x1,y1,x2,y2 :
1 3 5 7
<class 'float'>


In [60]:
print("Enter point to check :")
(Px,Py) = map(float, input().split())

Enter point to check :
2 4


In [61]:
if (Px >= x1 and Px < x2) and (Py > y1 and Py < y2):
    print("The point is inside a rectangle.")
else:
    print("The point is outside a rectangle.")

The point is inside a rectangle.


# Problem 3 - NumPy ndarray Manupulation Operations

In [62]:
# 1. Reshape matrices: Very Common-Errors in Asssignments

A = np.random.rand(5,4)
print(A)

[[0.05113996 0.44427079 0.9434764  0.94880523]
 [0.50206149 0.86010107 0.21020642 0.09249536]
 [0.87711588 0.58646448 0.93110196 0.3526304 ]
 [0.50733194 0.48706608 0.13305903 0.24345291]
 [0.00689069 0.05295103 0.99218363 0.28279978]]


In [70]:
#Reshape into a vector row-major-order
###Read the documentation on Numpy reshape
print(np.reshape(A, 20, 'C'))

[0.05113996 0.44427079 0.9434764  0.94880523 0.50206149 0.86010107
 0.21020642 0.09249536 0.87711588 0.58646448 0.93110196 0.3526304
 0.50733194 0.48706608 0.13305903 0.24345291 0.00689069 0.05295103
 0.99218363 0.28279978]


In [72]:
#Reshape into a vector column-major-order
###Read the documentation on Numpy reshape
print(np.reshape(A, 20, 'F'))

[0.05113996 0.50206149 0.87711588 0.50733194 0.00689069 0.44427079
 0.86010107 0.58646448 0.48706608 0.05295103 0.9434764  0.21020642
 0.93110196 0.13305903 0.99218363 0.94880523 0.09249536 0.3526304
 0.24345291 0.28279978]


In [74]:
print(np.reshape(A, (2,-1)))

[[0.05113996 0.44427079 0.9434764  0.94880523 0.50206149 0.86010107
  0.21020642 0.09249536 0.87711588 0.58646448]
 [0.93110196 0.3526304  0.50733194 0.48706608 0.13305903 0.24345291
  0.00689069 0.05295103 0.99218363 0.28279978]]


# Exercise 3 - Take a tensor of size 4X5X6 and convert it into a vector and then matrix (10X12).

In [75]:
A = np.random.rand(4,5,6)
print(A)

[[[0.87899928 0.32806608 0.67599355 0.1570424  0.35562102 0.06793729]
  [0.00573163 0.96475368 0.33806579 0.54993761 0.88722031 0.19996662]
  [0.03340125 0.34373833 0.4657859  0.57651819 0.95130111 0.78546148]
  [0.45141289 0.0123125  0.91293576 0.51141928 0.43805962 0.40575964]
  [0.91197054 0.58854306 0.51927978 0.10783387 0.71175927 0.2306136 ]]

 [[0.74339871 0.43704041 0.72974205 0.5416254  0.1426532  0.92545293]
  [0.52893656 0.1236611  0.41677647 0.11673465 0.71959892 0.87319474]
  [0.48547294 0.88758696 0.46946577 0.79322338 0.61463234 0.95655646]
  [0.61469426 0.06446553 0.17835891 0.65191018 0.21444805 0.85495355]
  [0.34502307 0.14529637 0.68888723 0.46461202 0.2549214  0.10919744]]

 [[0.56161842 0.22774551 0.92425323 0.99562343 0.09851897 0.588801  ]
  [0.92204592 0.37916798 0.3724182  0.78233276 0.10841899 0.54227522]
  [0.44882012 0.27202124 0.02020797 0.41273539 0.69981064 0.66807804]
  [0.36840248 0.30358332 0.7362154  0.84626781 0.16275573 0.20628703]
  [0.66092795 0.

In [80]:
B = np.reshape(A, 120,'C')
print(B)

[0.87899928 0.32806608 0.67599355 0.1570424  0.35562102 0.06793729
 0.00573163 0.96475368 0.33806579 0.54993761 0.88722031 0.19996662
 0.03340125 0.34373833 0.4657859  0.57651819 0.95130111 0.78546148
 0.45141289 0.0123125  0.91293576 0.51141928 0.43805962 0.40575964
 0.91197054 0.58854306 0.51927978 0.10783387 0.71175927 0.2306136
 0.74339871 0.43704041 0.72974205 0.5416254  0.1426532  0.92545293
 0.52893656 0.1236611  0.41677647 0.11673465 0.71959892 0.87319474
 0.48547294 0.88758696 0.46946577 0.79322338 0.61463234 0.95655646
 0.61469426 0.06446553 0.17835891 0.65191018 0.21444805 0.85495355
 0.34502307 0.14529637 0.68888723 0.46461202 0.2549214  0.10919744
 0.56161842 0.22774551 0.92425323 0.99562343 0.09851897 0.588801
 0.92204592 0.37916798 0.3724182  0.78233276 0.10841899 0.54227522
 0.44882012 0.27202124 0.02020797 0.41273539 0.69981064 0.66807804
 0.36840248 0.30358332 0.7362154  0.84626781 0.16275573 0.20628703
 0.66092795 0.4278144  0.73246351 0.37870605 0.90530924 0.8628201

In [81]:
C = np.reshape(B, (10,12))
print(C)

[[0.87899928 0.32806608 0.67599355 0.1570424  0.35562102 0.06793729
  0.00573163 0.96475368 0.33806579 0.54993761 0.88722031 0.19996662]
 [0.03340125 0.34373833 0.4657859  0.57651819 0.95130111 0.78546148
  0.45141289 0.0123125  0.91293576 0.51141928 0.43805962 0.40575964]
 [0.91197054 0.58854306 0.51927978 0.10783387 0.71175927 0.2306136
  0.74339871 0.43704041 0.72974205 0.5416254  0.1426532  0.92545293]
 [0.52893656 0.1236611  0.41677647 0.11673465 0.71959892 0.87319474
  0.48547294 0.88758696 0.46946577 0.79322338 0.61463234 0.95655646]
 [0.61469426 0.06446553 0.17835891 0.65191018 0.21444805 0.85495355
  0.34502307 0.14529637 0.68888723 0.46461202 0.2549214  0.10919744]
 [0.56161842 0.22774551 0.92425323 0.99562343 0.09851897 0.588801
  0.92204592 0.37916798 0.3724182  0.78233276 0.10841899 0.54227522]
 [0.44882012 0.27202124 0.02020797 0.41273539 0.69981064 0.66807804
  0.36840248 0.30358332 0.7362154  0.84626781 0.16275573 0.20628703]
 [0.66092795 0.4278144  0.73246351 0.3787060

# Stacking

In [82]:
#Stacking

A = np.random.rand(5,4);
print(A)

B = np.random.rand(5,2)
print(B)

[[0.62147783 0.59776756 0.52651022 0.24838523]
 [0.88782141 0.67274947 0.95103286 0.84292144]
 [0.15359605 0.09434406 0.8972645  0.67152097]
 [0.41030907 0.2392253  0.54539492 0.79806558]
 [0.88537862 0.78595556 0.5528704  0.33983367]]
[[0.28943188 0.40690061]
 [0.06229569 0.58543188]
 [0.54553391 0.293665  ]
 [0.56364123 0.04110176]
 [0.93633626 0.67022825]]


In [86]:
#Horizontal Stacking
C = np.hstack((A,B))
print(C)

[[0.62147783 0.59776756 0.52651022 0.24838523 0.28943188 0.40690061]
 [0.88782141 0.67274947 0.95103286 0.84292144 0.06229569 0.58543188]
 [0.15359605 0.09434406 0.8972645  0.67152097 0.54553391 0.293665  ]
 [0.41030907 0.2392253  0.54539492 0.79806558 0.56364123 0.04110176]
 [0.88537862 0.78595556 0.5528704  0.33983367 0.93633626 0.67022825]]


In [87]:
A = np.random.rand(5,4)
print(A)

B = np.random.rand(4,4)
print(B)

C = np.hstack((A,B))
print(C)

[[0.37021379 0.87229454 0.47245044 0.50269144]
 [0.55103715 0.27062217 0.20025569 0.13545376]
 [0.42816059 0.77498053 0.12396434 0.64098872]
 [0.88972532 0.31295435 0.85023672 0.55525636]
 [0.66175887 0.21232844 0.44069549 0.94390054]]
[[0.04129736 0.89949021 0.28852076 0.87136342]
 [0.4849532  0.68831479 0.59480868 0.84987233]
 [0.30787342 0.77579157 0.75119421 0.95474468]
 [0.45932709 0.87772079 0.2938517  0.72868457]]


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 5 and the array at index 1 has size 4

In [88]:
#Vertical Stacking

C = np.vstack((A,B))
print(C)

[[0.37021379 0.87229454 0.47245044 0.50269144]
 [0.55103715 0.27062217 0.20025569 0.13545376]
 [0.42816059 0.77498053 0.12396434 0.64098872]
 [0.88972532 0.31295435 0.85023672 0.55525636]
 [0.66175887 0.21232844 0.44069549 0.94390054]
 [0.04129736 0.89949021 0.28852076 0.87136342]
 [0.4849532  0.68831479 0.59480868 0.84987233]
 [0.30787342 0.77579157 0.75119421 0.95474468]
 [0.45932709 0.87772079 0.2938517  0.72868457]]


In [95]:
#3D Tensors - H Stack
A = np.random.rand(5,4,3)
print(A.shape)
B = np.random.rand(5,3,3)
print(B.shape)

C = np.hstack((A,B))
print(C.shape)

print(C)

(5, 4, 3)
(5, 3, 3)
(5, 7, 3)
[[[7.67869893e-01 2.37792340e-01 8.40134340e-02]
  [6.04557638e-01 2.63163139e-01 5.28973433e-01]
  [4.48812338e-01 6.65459600e-01 3.12955620e-01]
  [2.60268706e-01 5.60610403e-01 5.71380063e-01]
  [8.78476853e-02 4.40808393e-01 8.59618299e-01]
  [7.20175315e-01 4.95729213e-02 2.79936519e-01]
  [9.17441059e-01 1.39433972e-01 6.03866442e-01]]

 [[1.01165365e-01 7.08387954e-01 8.64623567e-01]
  [8.17840906e-01 5.82896358e-01 3.69652922e-01]
  [1.90269434e-01 5.63421278e-01 8.07942137e-01]
  [8.95215189e-01 1.94358360e-02 8.96842897e-01]
  [6.19179835e-01 3.20691910e-01 8.75664110e-01]
  [1.38344417e-01 5.96617507e-01 6.36201194e-01]
  [5.95930256e-01 8.22331544e-01 6.09711120e-01]]

 [[5.97073632e-01 8.27681439e-01 2.71216394e-01]
  [3.38682477e-03 3.70346468e-01 6.18463261e-04]
  [7.89257426e-01 6.22330616e-02 9.55459393e-02]
  [8.81532148e-01 9.94417558e-01 7.00362131e-01]
  [3.00693220e-01 3.60865143e-01 2.05072675e-01]
  [3.53012691e-01 5.47053741e-01 1.

In [94]:
#3D Tensors - V stack

A = np.random.rand(5,4,3)
print(A.shape)

B = np.random.rand(4,4,3)
print(B.shape)

C = np.vstack((A,B))
print(C)

(5, 4, 3)
(4, 4, 3)
[[[0.43957187 0.92837741 0.06890813]
  [0.58743333 0.31158991 0.80347797]
  [0.92029898 0.85443379 0.44930236]
  [0.47339553 0.23755852 0.70560822]]

 [[0.25163899 0.333475   0.81120127]
  [0.1103014  0.89126759 0.3008924 ]
  [0.06031127 0.39454704 0.97062127]
  [0.50385255 0.72019151 0.17883804]]

 [[0.66132447 0.88701382 0.93269296]
  [0.41870465 0.56553058 0.79916199]
  [0.71706757 0.86986725 0.33169913]
  [0.0696107  0.62308108 0.56380927]]

 [[0.48424662 0.41410122 0.90237187]
  [0.29891975 0.92908551 0.08831874]
  [0.35245515 0.30249915 0.06699181]
  [0.98345916 0.68765356 0.49623396]]

 [[0.89804184 0.98407155 0.20208237]
  [0.3546117  0.93337234 0.87589767]
  [0.08860998 0.69389839 0.35915245]
  [0.26743156 0.89023187 0.83460243]]

 [[0.66970807 0.76417489 0.05513883]
  [0.65256686 0.4477846  0.94118184]
  [0.54441694 0.58465797 0.64723842]
  [0.54199164 0.56632662 0.20455152]]

 [[0.95669912 0.31548144 0.11692875]
  [0.31561131 0.55589473 0.53951541]
  [0.3