1. import numpy and print version number

In [2]:
import numpy as np
print(np.__version__)

1.20.3


2. Create a 1D array

In [9]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3. Create a Boolean Array

In [11]:
a = np.full((3,3), True, dtype=bool)
a

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [12]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

4. Extract all Odd Numbers from 1D array

In [15]:
a = np.arange(10)
a[1:10:2] #One way

array([1, 3, 5, 7, 9])

In [17]:
#second way
a = a[a % 2 == 1]
a

array([1, 3, 5, 7, 9])

5. Replace all odd numbers in array in -1 (with another value in Numpy Array)

In [19]:
b = np.arange(10)
b[b % 2 == 1] = -1
b

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

6. Replace all odd numbers in array with -1 without changing original array

In [21]:
a = np.arange(10)

#Use of Where function
b = np.where(a % 2 == 1, -1, a)
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## This is the first time I have used where function so apparently allows to replace values with specific condition applied on it.

7. Convert a 1D Array to a 2D Array with 2 rows. (Reshape an Array)

In [28]:
a = np.arange(10)

#reshape(rows,columns) = Setting -1 to automatically decides the number of columns
a.reshape(2, -1)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

8. How to Stack Two arrays Vertically -- Stack arrays a and b vertically

In [33]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

#Using Concatenate
c = np.concatenate([a,b], axis=0)
print(c)

print('**************************')

#Using Vertical Stack function
d = np.vstack([a,b])
print(d)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
**************************
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


9. How to stack two arrays Horizontally -- Stack the arrays a and b Horizontally

In [35]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)

#Using Concatenate
c = np.concatenate([a,b], axis=1)
print(c)

print("****************")

#Using hstack function
d = np.hstack([a,b])
print(d)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
****************
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


10. Generating Custom Sequences - Create the following pattern without hardcoding array[1,1,1,2,2,2,3,3,3,1,2,3,1,2,3,1,2,3] Using only Numpy functions and below a

In [39]:
a = np.array([1,2,3])

#Using r_ : r_ is used to concatenate along the first axis
b = np.r_[np.repeat(a,3), np.tile(a,3)]
print(b)

#Using Concatenate Function
c = np.concatenate([np.repeat(a,3), np.tile(a,3)])
print(c)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


11. Get common items between two python numpy arrays. (a and b)

In [47]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

__intersect1d = Returns the common value present in both the Sets.__

12. Remove from one array those items that exist in another -- From array a remove all items present in array b

In [48]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a,b)

array([1, 2, 3, 4])

__setdiff1d = To find the value present in the first set that are not present in the second set__

13. Get the Positions where elements of Two Match -- Get the positions where elements of a and b match

In [49]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

14. Extract all numbers between a given range from a numpy array -- Get all items between 5 and 10 from a

In [55]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

#Method 1
index = np.where((a >= 5) & (a <= 10))
print(a[index])

print('**************************')

#Method 2
a[(a >= 5) & (a <= 10)]


[ 6  9 10]
**************************


array([ 6,  9, 10])

15. Make a python function that handles scalars to word on Numpy Arrays -- Convert the function `maxx` that works on two scalars, to work on two arrays.

def maxx(x,y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
        
- maxx(1,5)


In [60]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

In [62]:
def maxx(x,y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
    

In [64]:
pair_max = np.vectorize(maxx, otypes=[float])
pair_max(a,b)

array([6., 7., 9., 8., 9., 7., 5.])

16. Swap two columns in a 2D numpy array -- Swap columns 1 and 2 in the array 

In [65]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [66]:
a[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

17. Swap two rows in a 2D numpy array - Swap rows 1 and 2 in the array

In [67]:
a = np.arange(9).reshape(3,-1)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [69]:
a[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

18. Reverse the rows of a 2D array -- Reverse the rows of a 2D array

In [72]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [78]:
a[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

19. Reverse the columns of 2D array -- Reverse the columns of a 2D array

In [79]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [80]:
#Method 1
a[:,[2,1,0]]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [81]:
#Method 2

a[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

20. Create a 2D array containing random floats between 5 and 10 -- Create a 2D array of shape 5 x 3 to contain random decimal numbers between 5 and 10

In [87]:
rand_array = np.random.uniform(low=5, high= 10, size=(5,3))
print(rand_array)

[[7.59748892 9.0964333  7.14506309]
 [7.0908042  5.74677434 9.88082236]
 [7.59062347 9.84711884 6.81632407]
 [6.77235848 8.9239509  6.32827937]
 [9.75837841 5.30210159 6.48837517]]


__numpy.random. uniform (low=0.0, high=1.0, size=None) Draw samples from a uniform distribution. Samples are uniformly distributed over the half-open interval [low, high) (includes low, but excludes high). In other words, any value within the given interval is equally likely to be drawn by uniform .__

https://www.machinelearningplus.com/python/101-numpy-exercises-python/

21. Print only 3 decimal places in python numpy array - Print or show only 3 decimal places of the numpy array  rand_arr.

In [24]:
np.random.seed(100)
rand_arr = np.round_(np.random.random((5,3)), 3)
rand_arr

array([[0.543, 0.278, 0.425],
       [0.845, 0.005, 0.122],
       [0.671, 0.826, 0.137],
       [0.575, 0.891, 0.209],
       [0.185, 0.108, 0.22 ]])

22. Print a numpy array by supressing the scientific notation (like 1e10) -- Pretty print rand_arr by supressing the scientific notation like 1e10.

In [12]:
rand_arr = np.random.random((5,3))/1e3
rand_arr

array([[6.80858575e-04, 9.86459818e-04, 4.87259200e-04],
       [2.46665114e-04, 6.01997252e-04, 2.58309547e-05],
       [3.53822039e-04, 2.05507915e-05, 6.57677082e-04],
       [1.92901225e-04, 9.93820145e-04, 7.12057667e-04],
       [6.71985188e-04, 3.95850266e-04, 6.87109932e-04]])

In [21]:
np.info(np.set_printoptions)

 set_printoptions(precision=None, threshold=None, edgeitems=None,
                  linewidth=None, suppress=None, nanstr=None, infstr=None,
                  formatter=None, sign=None, floatmode=None, *, legacy=None)

Set printing options.

These options determine the way floating point numbers, arrays and
other NumPy objects are displayed.

Parameters
----------
precision : int or None, optional
    Number of digits of precision for floating point output (default 8).
    May be None if `floatmode` is not `fixed`, to print as many digits as
    necessary to uniquely specify the value.
threshold : int, optional
    Total number of array elements which trigger summarization
    rather than full repr (default 1000).
    To always use the full repr without summarization, pass `sys.maxsize`.
edgeitems : int, optional
    Number of array items in summary at beginning and end of
    each dimension (default 3).
linewidth : int, optional
    The number of characters per line for the purpose of

In [15]:
np.set_printoptions(suppress=True)

print(rand_arr)

[[0.00068086 0.00098646 0.00048726]
 [0.00024667 0.000602   0.00002583]
 [0.00035382 0.00002055 0.00065768]
 [0.0001929  0.00099382 0.00071206]
 [0.00067199 0.00039585 0.00068711]]


23. Limit the number of items printed in output of numpy array -- Limit the number of items printed in output of numpy array a to maximum number of 6 element 

In [19]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
np.set_printoptions(threshold = 6)
print(a)

[ 0  1  2 ... 12 13 14]


24. Print the full numpy array without truncating -- Print the full numpy array a without truncating.

In [25]:
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [41]:
np.set_printoptions(threshold=1000)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

25. Import a dataset with numbers and texts keeping the intact in python numpy. -- Import iris dataset keeping the text intact.

In [66]:
a = np.genfromtxt('iris.data', delimiter =',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
a[:3]


array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

26. Extract a particular column from 1D array of tuples -- Extract the columns species from 1D iris imported in previous sections

In [90]:
species = np.array([col[4] for col in a])
print(species.shape)

print(species[:5])

(150,)
[b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa']


In [88]:
species = np.array([col[4] for col in a])
print(species.shape)

b = species[20:]
print(b.shape)

c = species[:5]
print(c.shape)

(150,)
(130,)
(5,)


27. Convert a 1D array of tuples to 2D numpy array -- Convert a 1D iris to 2D array by omitting the species text field

In [94]:
species_1d = np.genfromtxt('iris.data', delimiter = ',' , dtype=None)

species_2d = np.array([row.tolist()[:4] for row in species_1d])
species_2d[:5]

C:\Users\Asus\AppData\Local\Temp/ipykernel_3476/1284445418.py:1: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  species_1d = np.genfromtxt('iris.data', delimiter = ',' , dtype=None)


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [96]:
species_twod = np.genfromtxt('iris.data', delimiter = ',' , dtype=float, usecols = [0,1,2,3])
species_twod[:5]


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [103]:
c = species_1d.tolist()
c[0][4]

b'Iris-setosa'

28. Computer mean, median, standar deviation of a numpy array -- Find mean, median and standard deviation of iris's sepallength


In [114]:
sepal_length = np.genfromtxt('iris.data',delimiter = ',' , dtype=None, usecols=[0])

sepal_l = sepal_length.tolist()

sepal_l[:5]



[5.1, 4.9, 4.7, 4.6, 5.0]

In [117]:
sepal_length.mean()

5.843333333333334

In [122]:
np.median(sepal_l)

5.8

In [121]:
np.std(sepal_l)

0.8253012917851409